#!/bin/bash
echo "=== macOS 環境チェック ==="
echo ""
echo "OS: $(sw_vers -productName) $(sw_vers -productVersion)"
echo "CPU: $(uname -m)"
echo ""
echo "--- ツール確認 ---"
command -v brew    &>/dev/null && echo "✅ Homebrew: $(brew --version | head -1)" || echo "❌ Homebrew: 未インストール"
command -v wine    &>/dev/null && echo "✅ Wine: $(wine --version)"    || echo "❌ Wine: 未インストール"
command -v wine64  &>/dev/null && echo "✅ Wine64: $(wine64 --version)" || echo ""
command -v python3 &>/dev/null && echo "✅ Python: $(python3 --version)" || echo "❌ Python3: なし"
echo ""
echo "--- デスクトップ確認 ---"
ls -la "$HOME/Desktop/SBK_Performance_Tool.exe" 2>/dev/null && echo "✅ exe: あり" || echo "❌ exe: なし"
ls -la "$HOME/Desktop/_internal/" 2>/dev/null | head -5 && echo "✅ _internal: あり" || echo "❌ _internal: なし"
echo ""
read -p "確認完了。Enterで閉じる..."
