-- Supabase cleanup 提案（remote_extra のみ） — 20260702
-- 生成: supabase_audit.py（read-only 監査）。
-- ⚠️ 自動実行禁止。各 DELETE の前に必ず SELECT で対象を確認し、Tatsuki が手動実行すること。
-- remote_extra = Supabase にあって local 正本(ts24_unified.db)の sync 投影に存在しない行。
-- NULLS NOT DISTINCT 対応のため IS NOT DISTINCT FROM を使用。

-- ===== race_results: remote_extra 0 件 =====
-- （差分なし）

-- ===== lap_times: remote_extra 0 件 =====
-- （差分なし）

-- ===== sessions_2d: remote_extra 13 件 =====
-- SELECT * FROM sessions_2d WHERE round IS NOT DISTINCT FROM '' AND circuit IS NOT DISTINCT FROM 'JEREZ' AND session_type IS NOT DISTINCT FROM 'TEST1_DAY1' AND rider IS NOT DISTINCT FROM 'DA77' AND run_no IS NOT DISTINCT FROM 1 AND date IS NOT DISTINCT FROM NULL;
DELETE FROM sessions_2d
  WHERE round IS NOT DISTINCT FROM ''
    AND circuit IS NOT DISTINCT FROM 'JEREZ'
    AND session_type IS NOT DISTINCT FROM 'TEST1_DAY1'
    AND rider IS NOT DISTINCT FROM 'DA77'
    AND run_no IS NOT DISTINCT FROM 1
    AND date IS NOT DISTINCT FROM NULL;

-- SELECT * FROM sessions_2d WHERE round IS NOT DISTINCT FROM '' AND circuit IS NOT DISTINCT FROM 'JEREZ' AND session_type IS NOT DISTINCT FROM 'TEST1_DAY1' AND rider IS NOT DISTINCT FROM 'DA77' AND run_no IS NOT DISTINCT FROM 2 AND date IS NOT DISTINCT FROM NULL;
DELETE FROM sessions_2d
  WHERE round IS NOT DISTINCT FROM ''
    AND circuit IS NOT DISTINCT FROM 'JEREZ'
    AND session_type IS NOT DISTINCT FROM 'TEST1_DAY1'
    AND rider IS NOT DISTINCT FROM 'DA77'
    AND run_no IS NOT DISTINCT FROM 2
    AND date IS NOT DISTINCT FROM NULL;

-- SELECT * FROM sessions_2d WHERE round IS NOT DISTINCT FROM '' AND circuit IS NOT DISTINCT FROM 'JEREZ' AND session_type IS NOT DISTINCT FROM 'TEST1_DAY1' AND rider IS NOT DISTINCT FROM 'DA77' AND run_no IS NOT DISTINCT FROM 3 AND date IS NOT DISTINCT FROM NULL;
DELETE FROM sessions_2d
  WHERE round IS NOT DISTINCT FROM ''
    AND circuit IS NOT DISTINCT FROM 'JEREZ'
    AND session_type IS NOT DISTINCT FROM 'TEST1_DAY1'
    AND rider IS NOT DISTINCT FROM 'DA77'
    AND run_no IS NOT DISTINCT FROM 3
    AND date IS NOT DISTINCT FROM NULL;

-- SELECT * FROM sessions_2d WHERE round IS NOT DISTINCT FROM '' AND circuit IS NOT DISTINCT FROM 'JEREZ' AND session_type IS NOT DISTINCT FROM 'TEST1_DAY1' AND rider IS NOT DISTINCT FROM 'DA77' AND run_no IS NOT DISTINCT FROM 4 AND date IS NOT DISTINCT FROM NULL;
DELETE FROM sessions_2d
  WHERE round IS NOT DISTINCT FROM ''
    AND circuit IS NOT DISTINCT FROM 'JEREZ'
    AND session_type IS NOT DISTINCT FROM 'TEST1_DAY1'
    AND rider IS NOT DISTINCT FROM 'DA77'
    AND run_no IS NOT DISTINCT FROM 4
    AND date IS NOT DISTINCT FROM NULL;

-- SELECT * FROM sessions_2d WHERE round IS NOT DISTINCT FROM '' AND circuit IS NOT DISTINCT FROM 'JEREZ' AND session_type IS NOT DISTINCT FROM 'TEST1_DAY1' AND rider IS NOT DISTINCT FROM 'DA77' AND run_no IS NOT DISTINCT FROM 5 AND date IS NOT DISTINCT FROM NULL;
DELETE FROM sessions_2d
  WHERE round IS NOT DISTINCT FROM ''
    AND circuit IS NOT DISTINCT FROM 'JEREZ'
    AND session_type IS NOT DISTINCT FROM 'TEST1_DAY1'
    AND rider IS NOT DISTINCT FROM 'DA77'
    AND run_no IS NOT DISTINCT FROM 5
    AND date IS NOT DISTINCT FROM NULL;

-- SELECT * FROM sessions_2d WHERE round IS NOT DISTINCT FROM '' AND circuit IS NOT DISTINCT FROM 'JEREZ' AND session_type IS NOT DISTINCT FROM 'TEST1_DAY1' AND rider IS NOT DISTINCT FROM 'DA77' AND run_no IS NOT DISTINCT FROM 6 AND date IS NOT DISTINCT FROM NULL;
DELETE FROM sessions_2d
  WHERE round IS NOT DISTINCT FROM ''
    AND circuit IS NOT DISTINCT FROM 'JEREZ'
    AND session_type IS NOT DISTINCT FROM 'TEST1_DAY1'
    AND rider IS NOT DISTINCT FROM 'DA77'
    AND run_no IS NOT DISTINCT FROM 6
    AND date IS NOT DISTINCT FROM NULL;

-- SELECT * FROM sessions_2d WHERE round IS NOT DISTINCT FROM '' AND circuit IS NOT DISTINCT FROM 'JEREZ' AND session_type IS NOT DISTINCT FROM 'TEST1_DAY1' AND rider IS NOT DISTINCT FROM 'DA77' AND run_no IS NOT DISTINCT FROM 7 AND date IS NOT DISTINCT FROM NULL;
DELETE FROM sessions_2d
  WHERE round IS NOT DISTINCT FROM ''
    AND circuit IS NOT DISTINCT FROM 'JEREZ'
    AND session_type IS NOT DISTINCT FROM 'TEST1_DAY1'
    AND rider IS NOT DISTINCT FROM 'DA77'
    AND run_no IS NOT DISTINCT FROM 7
    AND date IS NOT DISTINCT FROM NULL;

-- SELECT * FROM sessions_2d WHERE round IS NOT DISTINCT FROM '' AND circuit IS NOT DISTINCT FROM 'JEREZ' AND session_type IS NOT DISTINCT FROM 'TEST1_DAY2' AND rider IS NOT DISTINCT FROM 'DA77' AND run_no IS NOT DISTINCT FROM 1 AND date IS NOT DISTINCT FROM NULL;
DELETE FROM sessions_2d
  WHERE round IS NOT DISTINCT FROM ''
    AND circuit IS NOT DISTINCT FROM 'JEREZ'
    AND session_type IS NOT DISTINCT FROM 'TEST1_DAY2'
    AND rider IS NOT DISTINCT FROM 'DA77'
    AND run_no IS NOT DISTINCT FROM 1
    AND date IS NOT DISTINCT FROM NULL;

-- SELECT * FROM sessions_2d WHERE round IS NOT DISTINCT FROM '' AND circuit IS NOT DISTINCT FROM 'JEREZ' AND session_type IS NOT DISTINCT FROM 'TEST1_DAY2' AND rider IS NOT DISTINCT FROM 'DA77' AND run_no IS NOT DISTINCT FROM 2 AND date IS NOT DISTINCT FROM NULL;
DELETE FROM sessions_2d
  WHERE round IS NOT DISTINCT FROM ''
    AND circuit IS NOT DISTINCT FROM 'JEREZ'
    AND session_type IS NOT DISTINCT FROM 'TEST1_DAY2'
    AND rider IS NOT DISTINCT FROM 'DA77'
    AND run_no IS NOT DISTINCT FROM 2
    AND date IS NOT DISTINCT FROM NULL;

-- SELECT * FROM sessions_2d WHERE round IS NOT DISTINCT FROM '' AND circuit IS NOT DISTINCT FROM 'JEREZ' AND session_type IS NOT DISTINCT FROM 'TEST1_DAY2' AND rider IS NOT DISTINCT FROM 'DA77' AND run_no IS NOT DISTINCT FROM 3 AND date IS NOT DISTINCT FROM NULL;
DELETE FROM sessions_2d
  WHERE round IS NOT DISTINCT FROM ''
    AND circuit IS NOT DISTINCT FROM 'JEREZ'
    AND session_type IS NOT DISTINCT FROM 'TEST1_DAY2'
    AND rider IS NOT DISTINCT FROM 'DA77'
    AND run_no IS NOT DISTINCT FROM 3
    AND date IS NOT DISTINCT FROM NULL;

-- SELECT * FROM sessions_2d WHERE round IS NOT DISTINCT FROM '' AND circuit IS NOT DISTINCT FROM 'JEREZ' AND session_type IS NOT DISTINCT FROM 'TEST1_DAY2' AND rider IS NOT DISTINCT FROM 'DA77' AND run_no IS NOT DISTINCT FROM 4 AND date IS NOT DISTINCT FROM NULL;
DELETE FROM sessions_2d
  WHERE round IS NOT DISTINCT FROM ''
    AND circuit IS NOT DISTINCT FROM 'JEREZ'
    AND session_type IS NOT DISTINCT FROM 'TEST1_DAY2'
    AND rider IS NOT DISTINCT FROM 'DA77'
    AND run_no IS NOT DISTINCT FROM 4
    AND date IS NOT DISTINCT FROM NULL;

-- SELECT * FROM sessions_2d WHERE round IS NOT DISTINCT FROM '' AND circuit IS NOT DISTINCT FROM 'JEREZ' AND session_type IS NOT DISTINCT FROM 'TEST1_DAY2' AND rider IS NOT DISTINCT FROM 'DA77' AND run_no IS NOT DISTINCT FROM 5 AND date IS NOT DISTINCT FROM NULL;
DELETE FROM sessions_2d
  WHERE round IS NOT DISTINCT FROM ''
    AND circuit IS NOT DISTINCT FROM 'JEREZ'
    AND session_type IS NOT DISTINCT FROM 'TEST1_DAY2'
    AND rider IS NOT DISTINCT FROM 'DA77'
    AND run_no IS NOT DISTINCT FROM 5
    AND date IS NOT DISTINCT FROM NULL;

-- SELECT * FROM sessions_2d WHERE round IS NOT DISTINCT FROM '' AND circuit IS NOT DISTINCT FROM 'JEREZ' AND session_type IS NOT DISTINCT FROM 'TEST1_DAY2' AND rider IS NOT DISTINCT FROM 'DA77' AND run_no IS NOT DISTINCT FROM 6 AND date IS NOT DISTINCT FROM NULL;
DELETE FROM sessions_2d
  WHERE round IS NOT DISTINCT FROM ''
    AND circuit IS NOT DISTINCT FROM 'JEREZ'
    AND session_type IS NOT DISTINCT FROM 'TEST1_DAY2'
    AND rider IS NOT DISTINCT FROM 'DA77'
    AND run_no IS NOT DISTINCT FROM 6
    AND date IS NOT DISTINCT FROM NULL;

-- ===== lap_times_2d: remote_extra 11 件 =====
-- SELECT * FROM lap_times_2d WHERE round IS NOT DISTINCT FROM 'ROUND1' AND circuit IS NOT DISTINCT FROM 'PHILLIPISLAND' AND session_type IS NOT DISTINCT FROM 'RACE1' AND rider IS NOT DISTINCT FROM 'DA77' AND run_no IS NOT DISTINCT FROM 1 AND lap_no IS NOT DISTINCT FROM 1 AND date IS NOT DISTINCT FROM '2026-02-20';
DELETE FROM lap_times_2d
  WHERE round IS NOT DISTINCT FROM 'ROUND1'
    AND circuit IS NOT DISTINCT FROM 'PHILLIPISLAND'
    AND session_type IS NOT DISTINCT FROM 'RACE1'
    AND rider IS NOT DISTINCT FROM 'DA77'
    AND run_no IS NOT DISTINCT FROM 1
    AND lap_no IS NOT DISTINCT FROM 1
    AND date IS NOT DISTINCT FROM '2026-02-20';

-- SELECT * FROM lap_times_2d WHERE round IS NOT DISTINCT FROM 'ROUND1' AND circuit IS NOT DISTINCT FROM 'PHILLIPISLAND' AND session_type IS NOT DISTINCT FROM 'RACE1' AND rider IS NOT DISTINCT FROM 'JA52' AND run_no IS NOT DISTINCT FROM 1 AND lap_no IS NOT DISTINCT FROM 1 AND date IS NOT DISTINCT FROM '2026-02-20';
DELETE FROM lap_times_2d
  WHERE round IS NOT DISTINCT FROM 'ROUND1'
    AND circuit IS NOT DISTINCT FROM 'PHILLIPISLAND'
    AND session_type IS NOT DISTINCT FROM 'RACE1'
    AND rider IS NOT DISTINCT FROM 'JA52'
    AND run_no IS NOT DISTINCT FROM 1
    AND lap_no IS NOT DISTINCT FROM 1
    AND date IS NOT DISTINCT FROM '2026-02-20';

-- SELECT * FROM lap_times_2d WHERE round IS NOT DISTINCT FROM 'ROUND1' AND circuit IS NOT DISTINCT FROM 'PHILLIPISLAND' AND session_type IS NOT DISTINCT FROM 'RACE1' AND rider IS NOT DISTINCT FROM 'JA52' AND run_no IS NOT DISTINCT FROM 2 AND lap_no IS NOT DISTINCT FROM 1 AND date IS NOT DISTINCT FROM '2026-02-20';
DELETE FROM lap_times_2d
  WHERE round IS NOT DISTINCT FROM 'ROUND1'
    AND circuit IS NOT DISTINCT FROM 'PHILLIPISLAND'
    AND session_type IS NOT DISTINCT FROM 'RACE1'
    AND rider IS NOT DISTINCT FROM 'JA52'
    AND run_no IS NOT DISTINCT FROM 2
    AND lap_no IS NOT DISTINCT FROM 1
    AND date IS NOT DISTINCT FROM '2026-02-20';

-- SELECT * FROM lap_times_2d WHERE round IS NOT DISTINCT FROM 'ROUND1' AND circuit IS NOT DISTINCT FROM 'PHILLIPISLAND' AND session_type IS NOT DISTINCT FROM 'RACE2' AND rider IS NOT DISTINCT FROM 'DA77' AND run_no IS NOT DISTINCT FROM 1 AND lap_no IS NOT DISTINCT FROM 1 AND date IS NOT DISTINCT FROM '2026-02-20';
DELETE FROM lap_times_2d
  WHERE round IS NOT DISTINCT FROM 'ROUND1'
    AND circuit IS NOT DISTINCT FROM 'PHILLIPISLAND'
    AND session_type IS NOT DISTINCT FROM 'RACE2'
    AND rider IS NOT DISTINCT FROM 'DA77'
    AND run_no IS NOT DISTINCT FROM 1
    AND lap_no IS NOT DISTINCT FROM 1
    AND date IS NOT DISTINCT FROM '2026-02-20';

-- SELECT * FROM lap_times_2d WHERE round IS NOT DISTINCT FROM 'ROUND1' AND circuit IS NOT DISTINCT FROM 'PHILLIPISLAND' AND session_type IS NOT DISTINCT FROM 'RACE2' AND rider IS NOT DISTINCT FROM 'JA52' AND run_no IS NOT DISTINCT FROM 1 AND lap_no IS NOT DISTINCT FROM 1 AND date IS NOT DISTINCT FROM '2025-02-21';
DELETE FROM lap_times_2d
  WHERE round IS NOT DISTINCT FROM 'ROUND1'
    AND circuit IS NOT DISTINCT FROM 'PHILLIPISLAND'
    AND session_type IS NOT DISTINCT FROM 'RACE2'
    AND rider IS NOT DISTINCT FROM 'JA52'
    AND run_no IS NOT DISTINCT FROM 1
    AND lap_no IS NOT DISTINCT FROM 1
    AND date IS NOT DISTINCT FROM '2025-02-21';

-- SELECT * FROM lap_times_2d WHERE round IS NOT DISTINCT FROM 'ROUND1' AND circuit IS NOT DISTINCT FROM 'PHILLIPISLAND' AND session_type IS NOT DISTINCT FROM 'RACE2' AND rider IS NOT DISTINCT FROM 'JA52' AND run_no IS NOT DISTINCT FROM 1 AND lap_no IS NOT DISTINCT FROM 1 AND date IS NOT DISTINCT FROM '2026-02-20';
DELETE FROM lap_times_2d
  WHERE round IS NOT DISTINCT FROM 'ROUND1'
    AND circuit IS NOT DISTINCT FROM 'PHILLIPISLAND'
    AND session_type IS NOT DISTINCT FROM 'RACE2'
    AND rider IS NOT DISTINCT FROM 'JA52'
    AND run_no IS NOT DISTINCT FROM 1
    AND lap_no IS NOT DISTINCT FROM 1
    AND date IS NOT DISTINCT FROM '2026-02-20';

-- SELECT * FROM lap_times_2d WHERE round IS NOT DISTINCT FROM 'ROUND3' AND circuit IS NOT DISTINCT FROM 'ASSEN' AND session_type IS NOT DISTINCT FROM 'RACE1' AND rider IS NOT DISTINCT FROM 'DA77' AND run_no IS NOT DISTINCT FROM 1 AND lap_no IS NOT DISTINCT FROM 1 AND date IS NOT DISTINCT FROM '2026-04-25';
DELETE FROM lap_times_2d
  WHERE round IS NOT DISTINCT FROM 'ROUND3'
    AND circuit IS NOT DISTINCT FROM 'ASSEN'
    AND session_type IS NOT DISTINCT FROM 'RACE1'
    AND rider IS NOT DISTINCT FROM 'DA77'
    AND run_no IS NOT DISTINCT FROM 1
    AND lap_no IS NOT DISTINCT FROM 1
    AND date IS NOT DISTINCT FROM '2026-04-25';

-- SELECT * FROM lap_times_2d WHERE round IS NOT DISTINCT FROM 'ROUND5' AND circuit IS NOT DISTINCT FROM 'MOST' AND session_type IS NOT DISTINCT FROM 'RACE1' AND rider IS NOT DISTINCT FROM 'DA77' AND run_no IS NOT DISTINCT FROM 1 AND lap_no IS NOT DISTINCT FROM 1 AND date IS NOT DISTINCT FROM '2026-05-15';
DELETE FROM lap_times_2d
  WHERE round IS NOT DISTINCT FROM 'ROUND5'
    AND circuit IS NOT DISTINCT FROM 'MOST'
    AND session_type IS NOT DISTINCT FROM 'RACE1'
    AND rider IS NOT DISTINCT FROM 'DA77'
    AND run_no IS NOT DISTINCT FROM 1
    AND lap_no IS NOT DISTINCT FROM 1
    AND date IS NOT DISTINCT FROM '2026-05-15';

-- SELECT * FROM lap_times_2d WHERE round IS NOT DISTINCT FROM 'ROUND5' AND circuit IS NOT DISTINCT FROM 'MOST' AND session_type IS NOT DISTINCT FROM 'RACE1' AND rider IS NOT DISTINCT FROM 'JA52' AND run_no IS NOT DISTINCT FROM 1 AND lap_no IS NOT DISTINCT FROM 1 AND date IS NOT DISTINCT FROM '2026-05-15';
DELETE FROM lap_times_2d
  WHERE round IS NOT DISTINCT FROM 'ROUND5'
    AND circuit IS NOT DISTINCT FROM 'MOST'
    AND session_type IS NOT DISTINCT FROM 'RACE1'
    AND rider IS NOT DISTINCT FROM 'JA52'
    AND run_no IS NOT DISTINCT FROM 1
    AND lap_no IS NOT DISTINCT FROM 1
    AND date IS NOT DISTINCT FROM '2026-05-15';

-- SELECT * FROM lap_times_2d WHERE round IS NOT DISTINCT FROM 'ROUND5' AND circuit IS NOT DISTINCT FROM 'MOST' AND session_type IS NOT DISTINCT FROM 'RACE2' AND rider IS NOT DISTINCT FROM 'DA77' AND run_no IS NOT DISTINCT FROM 1 AND lap_no IS NOT DISTINCT FROM 1 AND date IS NOT DISTINCT FROM '2026-05-15';
DELETE FROM lap_times_2d
  WHERE round IS NOT DISTINCT FROM 'ROUND5'
    AND circuit IS NOT DISTINCT FROM 'MOST'
    AND session_type IS NOT DISTINCT FROM 'RACE2'
    AND rider IS NOT DISTINCT FROM 'DA77'
    AND run_no IS NOT DISTINCT FROM 1
    AND lap_no IS NOT DISTINCT FROM 1
    AND date IS NOT DISTINCT FROM '2026-05-15';

-- SELECT * FROM lap_times_2d WHERE round IS NOT DISTINCT FROM 'ROUND5' AND circuit IS NOT DISTINCT FROM 'MOST' AND session_type IS NOT DISTINCT FROM 'RACE2' AND rider IS NOT DISTINCT FROM 'JA52' AND run_no IS NOT DISTINCT FROM 1 AND lap_no IS NOT DISTINCT FROM 1 AND date IS NOT DISTINCT FROM '2026-05-15';
DELETE FROM lap_times_2d
  WHERE round IS NOT DISTINCT FROM 'ROUND5'
    AND circuit IS NOT DISTINCT FROM 'MOST'
    AND session_type IS NOT DISTINCT FROM 'RACE2'
    AND rider IS NOT DISTINCT FROM 'JA52'
    AND run_no IS NOT DISTINCT FROM 1
    AND lap_no IS NOT DISTINCT FROM 1
    AND date IS NOT DISTINCT FROM '2026-05-15';

